spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employee_service
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8050
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
  instance:
    prefer-ip-address: true
jwt:
  secret: "6a627a7fb025e2c5db643267523a1c801c1178bed30331a2606fe93f4dd9aa7b"