spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shift_service
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 8070
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
  instance:
    prefer-ip-address: true
jwt:
  secret: "CECF479371E92D21727A62A36B292"